config/routes.rb
Dealancers::Application.routes.draw do
  get "addme/index"

  match 'addme' => 'addme#index', :as => :addme
  match 'addme/create' => 'addme#create', :as => :create_deal

  get "home/index"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  

   root :to => 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  attr_accessible :description, :user_id
  belongs_to :user
  has_many :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :deal_id, :fb_photo_id, :name, :image
  belongs_to :deal

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, :uid
  has_many :deals

  def self.from_omniauth(auth)  	
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

end

app/controllers/addme_controller.rb
require 'open-uri'
class AddmeController < ApplicationController
  def index
  	graph = Koala::Facebook::GraphAPI.new(current_user.oauth_token)

	#friends = @graph.get_object("/me/albums", "fields"=>"name")
	#friends = @graph.get_object("me") {|data| data['education']} 

	#redirect_to session['oauth'].url_for_oauth_code(:permissions=>'friends_relationships')   
	#@graph.get_connections('me','friends',:fields=>"name,gender,relationship_status")

	#friends = @graph.get_connections('me','albums',:fields=>"name")

	#puts friends.inspect

	# @graph.get_connection("me", "albums", :fields => "name").each do |hash|
 #      puts "-------------->" + hash['name']
 #    end

    # @graph.get_object("me/albums?fields=name,photos.fields(picture)").each do |album|
    #   #puts "-------------->" + hash['photos']['data'].inspect
    # 	#puts album['name']

    # 	album['photos']['data'].each do |picture|
    # 		puts picture['picture']
    # 	end
    # end
	# @oauth = Koala::Facebook::OAuth.new(API_KEYS["facebook"]['app_id'], API_KEYS["facebook"]['app_secret'])
 #    puts @oauth.get_app_access_token.inspect

    @photos = graph.get_object(current_user.uid+"/albums?fields=name,photos.fields(picture,name)")
    #puts current_user.uid+"/albums?fields=name,photos.fields(picture,name)"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end

  end

  def create
    #oauth = Koala::Facebook::OAuth.new(API_KEYS["facebook"]['app_id'], API_KEYS["facebook"]['app_secret'])
    #oauth.url_for_oauth_code(:permissions => "email,user_location,user_about_me,user_photos")
    graph = Koala::Facebook::GraphAPI.new(current_user.oauth_token)
    #graph = Koala::Facebook::API.new(current_user.oauth_token)
    
    #feed = graph.get_connections("100001114368363", "photos")
    #feed = graph.get_object("448766258503849")
    #facebook_feed = ActiveSupport::JSON.decode(feed.to_json)
    #puts ">>>>>>>>>>>>>>>"+facebook_feed.inspect
    photos_id = params[:photos_id]

    deal = Deal.new
    deal.description = params[:description]
    deal.user = current_user
    
    photos_id.each do |p|
      
      fb_photo = graph.get_object("#{p.split('-')[1]}?fields=id,name,source")
      
      photo = Photo.new
      photo.fb_photo_id = fb_photo['id']
      photo.fb_album_id = p.split('-')[0]
      photo.name = fb_photo['name']
      photo.remote_image_url = fb_photo['source']
      
      deal.photos << photo

    end

    deal.save

    respond_to do |format|
          format.html { redirect_to root_path }
          format.js
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

   @oauth = Koala::Facebook::OAuth.new(API_KEYS["facebook"]['app_id'], API_KEYS["facebook"]['app_secret'], {:scope => 'email,user_location,user_about_me,user_photos', :display => 'popup'} )
   #puts "------> "+@oauth.get_app_access_token
   #  @graph_app = Koala::Facebook::API.new(@oauth.get_app_access_token)
  	@deals = Deal.all

   # 	@deals.each do |d|
   #     d.photos.each do |f|
   #     	puts @graph_app.get_object(f.fb_photo_id+"?fields=picture,name").inspect
   #     end
   # end

  # 	@fb_deals = graph.get_object(current_user.uid+"/albums?fields=name,photos.fields(picture,name)")
  #   puts @oauth.get_app_access_token.inspect


    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @oauth }
    end

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
        session[:user_id] = nil
        redirect_to root_url, :notice => "Signed out!"
  end

  def omniauth_failure
    redirect_to root_url, :notice => "Error Sign in!"
    #redirect wherever you want.
  end

end

app/helpers/addme_helper.rb
module AddmeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/addme/index.html.erb
<script type="text/javascript" src="/assets/jquery.wookmark.js"></script>
<script type="text/javascript">
$(function(){
  var total = $('#albums div').length;

  for(i = 0; i < total; i++){
    $('.row-fluid'+i+' .thumbnails li').wookmark({
      offset: 2,  
      container: $('.row-fluid'+i),
      autoResize: true
    });
  }
});
</script>
<div class="page-header">
  <h1>Agrega tu facebook <small><br>Selecciona tus albums o fotos y dinos que vendes</small></h1>
</div>

<%= form_tag(create_deal_path) do %>
<%= submit_tag 'Create deal!', :class => "btn btn-large btn-primary btn-block" %>
<br>

<label class="textarea">¿Qué vendes?<br>
<%= text_area_tag 'description' %>
</label>

<label class="checkbox">
  <%= check_box_tag "checkall" %>
      Seleccionar todo
</label>

    <div id="albums">
      <% @photos.each_with_index do |album, index| %>
            
              

              <div class="row-fluid<%= index %>">
                <label class="checkbox">
                  <input type="checkbox" class="checkAlbum" id="<%=album['id']%>">
                  <h4><%= album['name'] %></h4>
                </label>
                <ul class="thumbnails" style="position:relative">
                  <% if !album['photos'].nil? %>  
                  <% album['photos']['data'].each do |photo| %>
                  <li class="span2">
                    <div class="thumbnail">

                      <%= check_box_tag "photos_id[]", album['id']+"-"+photo['id']%>                                
                      <%= image_tag(photo['picture'])%>
                       
                      <div class="caption">
                      <p><%= photo['name'] %></p>
                      
                      </div>
                    </div>
                  </li> 
                  <% end %>
                  <% end %>
                </ul>    
              </div>     
      <% end %>
    </div>
<% end %>

app/views/home/index.html.erb
<div class="row-fluid">
  <ul class="thumbnails">
    <% @deals.each do |deal| %>                    
         <li class="span3">
          <div class="thumbnail">
            <%= image_tag("http://graph.facebook.com/#{deal.user.uid}/picture?type=large")%>
<div class="center">
             <ul class="thumbnails">
              <li class="span1">
            <%= image_tag("http://graph.facebook.com/#{deal.user.uid}/picture?type=small")%>
             </li>
             <li class="span1">
            <%= image_tag("http://graph.facebook.com/#{deal.user.uid}/picture?type=small")%>
             </li>
             <li class="span1">
            <%= image_tag("http://graph.facebook.com/#{deal.user.uid}/picture?type=small")%>
             </li>
             <li class="span1">
            <%= image_tag("http://graph.facebook.com/#{deal.user.uid}/picture?type=small")%>
             </li>
          </ul> 
</div>
              <div class="caption">
                <h3>Thumbnail label</h3>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a href="#" class="btn btn-primary">Ver Facebook</a> <a href="#" class="btn">Me gusta</a></p>
             </div>


          </div> 
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dealancers</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Dealancers", root_url, :class => "brand" %>
          <div class="nav-collapse collapse">
            

              <ul class="nav">
                <li>
                  <%= link_to 'Unirme!', addme_path%>
                </li>
                <li>
                  <form class="form-search">
  <div class="input-append">
    <input type="text" class="span2 search-query">
    <button type="submit" class="btn">Search</button>
  </div>
</form>
                </li>
                 <li>
                &nbsp;&nbsp;&nbsp;&nbsp;
                </li>
                <li>
                <% if current_user %>
                    <%= image_tag("http://graph.facebook.com/#{current_user.uid}/picture?type=square", :size => "40x40") %><strong><%= current_user.name %></strong>
                  <% else %>
                    <%= link_to "Entrar con Facebook", "/auth/facebook", id: "sign_in" %>
                  <% end %>
                </li>

                <li>
                <% if current_user %>
                  <%= link_to "Salir", signout_path, id: "sign_out" %>
                <% end %>
                </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

<div class="container-fluid">
  <div class="row-fluid">
    <!--<div class="span2 pull-right">
      Sidebar content
    </div>-->
    <div class="span10">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>